# .readthedocs.yml

# Required
version: 2

# Build documentation in the docs/ dir with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt